### ISSUE TITLE
What are the 2 folders created on startup?

### ISSUE THREAD

**Issue by joeblew99** [asticode/go-astilectron#42] opened 2017-09-08 17:09 UTC
Am using the latest demo project from osx.

When I run the eye on windows of the demo it creates 2 folders on startup.
Is this by design ?

Does not do that on osx.app

Btw the tray works on windows.

**Comment by asticode** [comment] 2017-09-09 08:21
This is by design **if you're using the bootstrap + bundler** (which is the case with the demo). If you're using `go-astilectron` on its own, you'll see only one folder, the `vendor` one which contains the `electron` + `astilectron` JS apps.

And the 2 folders are also created in osx at `/path/to/Astilectron Demo.app/Contents/MacOS`.

Does that answer your question?

**Comment by joeblew99** [comment] 2017-09-11 11:30
Thanks yes it does.
I guess i did not noticed it on OSX inside the Contents folder

Is there a way to avoid this i wonder.. If a golang server is started on a go routine, with the main GUI then can the golang server serve these assets to the GUI ?

**Comment by asticode** [comment] 2017-09-11 13:25
sure, but the golang server has to get the files from somewhere, and that's when you'll need a `resources` folder once again...

**Comment by joeblew99** [comment] 2017-09-12 09:08
Yes i have them on the mobiles, desktop as a service.. Just saying..

**Comment by joeblew99** [comment] 2017-09-18 08:56
let me explain my approach as it might help.

For desktop, you can have a golang service (which has all your golang and db code) and the GUI (which is the electorn app) running inside an initial process that forks to run both.

Others like me like to NOT have it forked. Instead the golang server runs as a service so its always there. The Electron GUI is just a normal app and the resources it needs are loaded from the service over http.

For Mobile you can also do exactly the same architecture with a service and the gui app as two seperate things.

**Comment by asticode** [comment] 2017-10-08 08:04
closing it here and will open a new issue in the bootstrap

**Closed by asticode** 2017-10-08 08:04 UTC
Labels: question
