### ISSUE TITLE
Suggestion to basic initializing screen

### ISSUE THREAD

**Issue by prsolucoes** [asticode/go-astilectron#17] opened 2017-06-01 19:17 UTC
Hi,

I search for a way to create a initializing screen, without depends on other reps. You dont need other libs. You can call per-platform their ui libraries. I search some references to you:

**1 - Windows (win api):**

Example creating window in c++:
https://github.com/LeZuse/minimal-win32-app/blob/master/main.cpp

Now in Go:
https://github.com/lxn/walk/blob/master/window.go

**2 - Linux (x11):**
https://github.com/golang/exp/blob/master/shiny/driver/x11driver/window.go

**3 - MacOS (cocoa):**
https://github.com/alediaferia/gogoa/blob/master/window.go

You dont need implement everything, but if we have a window with an image and a label showing what is happing and show the error (if have), we dont need more nothing, the rest if the main window in electron.

Thanks.

**Comment by asticode** [comment] 2017-06-02 08:02
Thanks for the suggestions @prsolucoes, I'll take a look it seems quite interesting. Also referenced your comment in the issue #16

**Comment by asticode** [comment] 2017-06-02 12:21
@prsolucoes the problem with per-platform ui libraries is that cross-platform building will be impossible. For instance it's impossible to build the `gogoa` project from a `UNIX` machine since MacOSX-specific ui libraries needed to build are not present in `UNIX` :(

**Comment by prsolucoes** [comment] 2017-06-02 13:53
Hi,

But if you use OpenGL for it? I think you can make it, no?

https://github.com/go-gl

Thanks.

**Comment by asticode** [comment] 2017-08-22 08:43
Closing this as it's a duplicate of #16 and it should stay the main thread (I've referenced this issue in #16 )

**Closed by asticode** 2017-08-22 08:43 UTC
Labels: duplicate
