### ISSUE TITLE
Taskbar (Windows 10)

### ISSUE THREAD

**Issue by shineoos** [asticode/go-astilectron#269] opened 2020-08-26 19:45 UTC
Everything works fine, even when I build, but when I add the app to the taskbar it adds electron and not my app

**Comment by asticode** [comment] 2020-08-28 09:55
What do you mean by "it adds electron and not my app" ? Maybe screenshots would  help.

**Comment by shineoos** [comment] 2020-08-28 15:54
![image](https://user-images.githubusercontent.com/59980769/91587655-5d99ab80-e957-11ea-9f3c-2922f83d438a.png)

this is added to the taskbar and when I start it it will start the default electron template
![image](https://user-images.githubusercontent.com/59980769/91587802-8f127700-e957-11ea-81a0-ba8ddf5c6873.png)

**Comment by asticode** [comment] 2020-08-31 09:20
Have you set [AppIconDefaultPath](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L66) ?

**Comment by shineoos** [comment] 2020-08-31 14:28
yes

**Comment by asticode** [comment] 2020-09-01 08:30
I think this is a duplicate of https://github.com/asticode/go-astilectron/issues/65

I'll close this issue, but do reopen it if you feel both issues are not the same

**Closed by asticode** 2020-09-01 08:30 UTC
Labels: need more information
