### ISSUE TITLE
how to build product file 

### ISSUE THREAD

**Issue by megimegikimmegi** [asticode/go-astilectron#205] opened 2019-11-04 08:32 UTC
i already know how to use go-astilecron-bundler 

Created exe file for use go-astilecron-bundler  but , that cannot excute other PC 

i think the ohter PC have not resuource file 

how to make exe file include resource file? 

now my source is 

AstilectronOptions: astilectron.Options{
			AppName:            AppName,
			AppIconDarwinPath:  "resources/icon.icns",
			AppIconDefaultPath: "resources/icon.png",
			DataDirectoryPath: "./",

and 

Windows: []*bootstrap.Window{{
			Homepage:       "/html/login.html",

....

**Comment by asticode** [comment] 2019-11-04 09:36
Duplicate of https://github.com/asticode/go-astilectron-demo/issues/52#.

Closing this one

**Closed by asticode** 2019-11-04 09:36 UTC
