### ISSUE TITLE
Implement a cross-platform splash screen

### ISSUE THREAD

**Issue by dmigwi** [asticode/go-astilectron#16] opened 2017-06-01 13:51 UTC
In My application, have decided to make the dependencies available in a specific folder once they are unzipped and configured by the default provisioner for the first time. The issue is that, the application gives a user a bad user experience especially the first time they run the application. The default provisioner takes quite sometime while running for the first time. Can we have a splash screen that appears while the default provisioner sets up the required dependencies configurations?

**Comment by asticode** [comment] 2017-06-01 14:10
There was a splash screen not long ago using [andlabs/ui](https://github.com/andlabs/ui) but I removed it because it was causing problem in MacOSX.

Unfortunately as of right now, I don't have any other idea on how to do it properly without adding to much complexity to this library.

If anyone has an idea, I'm opened to discussion since I do agree the first time wait is a big problem.

Anybody?

**Comment by andela-dmigwi** [comment] 2017-06-01 21:07
I have adopted a simple plan. I am trying to load only the basic dependencies before I display my customized splash screen. 

My implementation ends up loading first; the `electron`, `astilectron` and a few other dependencies needed to run the splash screen which are quite huge in terms of size. 

I think [asticode](https://github.com/asticode) if we found a mechanism where only the dependencies that display the splash are loaded first then the rest can be loaded while the splash screen is being displayed that would be great.

**Comment by veecue** [comment] 2017-06-01 22:51
There used to be something called loader, but it was removed due to platform specific problmesOn 1 Jun 2017 3:51 pm, andela-dmigwi <notifications@github.com> wrote:In My application, have decided to make the dependencies available in a specific folder once they are unzipped and configured by the default provisioner for the first time. The issue is that, the application gives a user a bad user experience especially the first time they run the application. The default provisioner takes quite sometime while running for the first time. Can we have a splash screen that appears while the default provisioner sets up the required dependencies configurations?

**Comment by lemtree** [comment] 2017-06-02 03:44
I have the same trouble.  and  use go build -ldflags="-H windowsgui" hide the cmd window, but the black cmd window will still display 0.1s，that terrible。

**Comment by asticode** [comment] 2017-06-02 07:39
@lemtree I think this is another issue, I'll open a new one specific to your problem

**Comment by asticode** [comment] 2017-06-02 07:57
@andela-dmigwi I totally agree with you, unfortunately the `basic dependencies` to open a window right now are `Electron` + `astilectron` which is pretty much everything. But I agree that we should find a way to load ligther dependencies first that would allow to show a splash screen while we load the rest of the dependencies.

My idea is to look for a simple way to display an image using C and see if it can be done without dependencies cross-platform. That way we would display the image using C while the dependencies are downloaded. I'll check this out, if anybody has an idea on how to do it, feel free to jump in :)

**Comment by asticode** [comment] 2017-06-02 08:00
Related comment: https://github.com/asticode/go-astilectron/issues/17#issue-232982135

**Comment by andela-dmigwi** [comment] 2017-06-02 08:11
@asticode that works too. Great, I can't wait to see the initialization screen up and running..

**Comment by andela-dmigwi** [comment] 2017-06-07 15:30
@asticode I have been doing some tests on the code, testing the exact time that each block of code takes to run .  

```// Create a new window
var w, _ = a.NewWindow("http://127.0.0.1:4000", &astilectron.WindowOptions{
    Center: astilectron.PtrBool(true),
    Height: astilectron.PtrInt(600),
    Width:  astilectron.PtrInt(600),
})
w.Create()
```

The above block of code consumes most of time before the initial window appears. On average it takes **629.3856925ms** to run than block of code on my machine. While the complete window appears after **970.839701ms**.

 Could reducing the time taken to execute that block of code fix our main issue?

**Comment by asticode** [comment] 2017-06-08 11:29
@andela-dmigwi the first run is what troubles me to be honest, when dependencies have not been installed or when the program is run for the first time after having powered off the computer. Either downloading all the dependencies takes time, or running Electron for the first time takes time as well.

I'd be interested in the average time it takes to show the window **when the program is run after having powered off the computer**. My bet is that it will be more than `5s`.

Therefore I don't see we'll find some other ways to make it more user-friendly other than displaying a splash screen.

**Comment by asticode** [comment] 2017-08-22 08:41
Hey guys, good news I've found time to work on the splash screen and I've came up with a solution that works on Linux et MacOS only for now (Windows will come shortly).

I would have prefered to tell you about it with Windows working as well, but my feeling is that it could still be beneficial to get your first thoughts/tests with both Linux and MacOS for starter.

The project is [astisplash](https://github.com/asticode/go-astisplash) and the way it works is pretty simple: to avoid using CGO that anihilates any hope to cross compile easily, the project executes already cross-compiled binaries that are embedded directly in GO.

The project's purpose should stay simple: display an image in a window and that's it.

The project as a short README that shows you how to use it but I've also created a `splash` branch in the `go-astilectron` project to ease testing: simply checkout the `splash` branch, delete your `example/vendor` folder (so that everything is downloaded all over again and it takes time to start your app) and run:

```
$ go run examples/9.splash_screen/main.go -v
```

What do you think?

**Comment by lemtree** [comment] 2017-08-25 14:50
@asticode That's really great

**Comment by joeblew99** [comment] 2017-09-18 08:51
You can use CGO fro cross platform builds. This was specifically built to handle this problem.
It also does mobile builds without using the gomobile stuff. 
It will allow you to then built react native apps for mobile with all the same asticode golang code with some adjustments. This is because react native supports web views as well as menus (native just like electron).

https://github.com/karalabe/xgo

This relies on using docker to built a proper golang cross build environment.

**Comment by asticode** [comment] 2017-12-23 09:34
Closing this issue and referencing [this one](https://github.com/asticode/go-astisplash/issues/1) instead

**Closed by asticode** 2017-12-23 09:34 UTC
Labels: enhancement
