### ISSUE TITLE
Zombie child process after close if debug window was opened

### ISSUE THREAD

**Issue by killerpd** [asticode/go-astilectron#208] opened 2019-12-27 16:09 UTC
I'd been running into a problem for a while with an electron process being left running after closing the main window.

This process rockets up from ~2% CPU while the main process is running, to ~25% after the applicatoin has "closed", which has a very detremental effect on the computer after it happens a few times.

After a bit of experimentation, it seems to reliably happen after opening the debug panel, and then closing the main window.

The core process shuts down, but it seems the debug window remains orphaned.

I'm relatively new to using astillectron with bootstrap, is there a way to find the list of active windows as it shuts down?
Similarly, it would be nice to have an event handler for when new windows are created, so that if they are created from the window (by JavaScript or otherwise) that the Go backend can be updated with their creation.

Ideally an end solution would be that on close, the application should clean up all active windows, so that it doesn't leave zombie children behind.

**Comment by asticode** [comment] 2019-12-28 10:47
@killerpd thanks for this very detailed issue.

Other `go-astilectron` users have been experiencing the same problem but that's the first time someone points out the dev tools window which seems like a good hypothesis to investigate.

What is weird is that the `js` code [quits the app properly when all windows are closed](https://github.com/asticode/astilectron/blob/master/index.js#L300). Do you quit the app manually in GO ?

**Comment by killerpd** [comment] 2020-01-14 14:02
If I do it by any means, it seems to reliably cause the same issue.

I still sometimes have a hung electron process after I close even if I haven't opened the dev tools, but opening the dev tools seems to reliably cause it.

I'm also running on Windows, if that might be a concern.

I have closed it by both closing the window (top right X), and by terminating the application.
Both seem to generally close down fine, without an orphaned process. But sometimes they will orphan a process.
I've been watching Task Manager when this happens to see if I can find what's going on.
Most of the time, the child processes close, then the parent process closes down.

Sometimes, however, one of the child processes looks like it separates from the set, as if it's no longer considered a child process, and that causes it to not close down with the rest.
Whether its a new process created at the point of closing, or actually a child process detaching, I'm not sure. Possibly even a child which is told to terminate, and doesn't properly?

I have found another way of more reliably causing an orphan child process.
If you have JS call window.close(), it much more regularly (though still not always) causes an orphaned process

I believe I have just observed one where the child process all close, leaving 1 remaing top level process, then another Electron process starts (and becomes an orphan), and the main process terminates.
This was triggered from calling `window.close()` from the only active window.

**Comment by killerpd** [comment] 2020-01-14 14:23
It looks like this Github issue was having the same issue, but it was resovled at Electron 1.4.7+, which astilectron seems to be running 4.0.1 so shouldn't be the same issue.

The most pertinent issues I've found are linked here:
https://github.com/electron/electron/issues/6120
https://github.com/segmentio/nightmare/issues/688

Both look like they were fixed by version bumps of Electron.
I've noticed that 4.0.1 is only just after the initial 4.x release of Electron, is there anything stopping bumping the core version with astilectron?

**Comment by asticode** [comment] 2020-01-14 14:42
@killerpd thanks for the very detailed comments once again :)

I don't think there's anything stopping us from bumping the Electron version.

The best would be that you bump the Electron version locally and see whether that fixes anything. 

If you're using the `bundler`, you'll need to use the `version_electron` option and make sure that you set Electron version in the bootstrap manually using the LDFlags (check [this](https://github.com/asticode/go-astilectron-demo/blob/master/main.go#L50)). If you're not using the bundler, simply update the version [here](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L17).

Let me know.

**Comment by dana321** [comment] 2020-01-14 22:51
I tried bumping up to the latest v4 branch (4.2.9), but that still had the same issue.

But I can confirm the latest electron 7.1.9 works fine and no longer has the problem of hanging processes.

**Comment by asticode** [comment] 2020-01-15 08:29
OK that's good to know. I don't see why we couldn't bump Electron's version to 7.1.9. I'll do some tests and bump the version if everything works as expected.

**Comment by adamlawson** [comment] 2020-01-23 21:50
Good call! I've just updated to 7.1.10, as far as I can tell, the only change needed in astilectron is 

`WebviewTag *bool  `json:"webviewTag,omitempty"`` to be added to the WebPreferences struct

Related issue: [https://github.com/asticode/go-astilectron/issues/163](url)

I'll try for a week or so and let you know if it's fixed the issue for me

**Comment by aeroplanelabs** [comment] 2020-01-23 23:56
We're having an issue with getting 7.1.9 to work on High Sierra, the older version works correctly but windows is 100% fine on 7.1.9

**Comment by asticode** [comment] 2020-01-24 09:18
@adamlawson why do we need to add this field for this specific issue ?

@aeroplanelabs I'm also experiencing issues from 6.0.0 in MacOSX. It seems the Test.app doesn't have a blocking pattern anymore...

**Comment by adamlawson** [comment] 2020-01-24 10:54
@asticode it's not for this issue, it's just a breaking change that I've noticed in Electron 7.1.10, as webviews default to disabled now

**Comment by asticode** [comment] 2020-01-24 11:33
@adamlawson OK makes sense

I've investigated the problems on MacOSX and here are the breaking changes :

- there are 4 frameworks now in the Electron.app instead of the one. Therefore, when renaming the `Helper` so that the proper name is displayed, the other frameworks can't find it anymore and the app stops working
- `nodeIntegration` is now `false` by default therefore the `executeJavascript` can't use the `require` keyword
- to load local files, they now must be listed in the `package.json` using the `files` key

As the last 2 changes are not MacOSX specific, I'm wondering how this is working on other platforms...

**Comment by adamlawson** [comment] 2020-01-24 11:37
`nodeIntegration` - same applies on Windows - I just set it to true and I'm only running trusted files.
The local files thing, I'm not so sure about, I haven't used it.

**Comment by adamlawson** [comment] 2020-02-06 21:47
Just an update, this definitely fixed the zombie process for me. I haven't looked at OS X support yet though

**Comment by asticode** [comment] 2020-02-07 14:19
OK this is good to know

**Comment by killerpd** [comment] 2020-02-07 17:21
Any idea how long it might take?
I've not got much experience with actually setting up electron, so I wouldn't really know where to start.
If you want more testing on a trial branch, I'd be happy to pull that down and work with it.

**Comment by asticode** [comment] 2020-02-08 10:20
Unfortunately I don't have much time to work on this issue right now 😞 

If you don't care about MacOSX and are using the bundler, you can force the electron version in the bundler configuration file.

**Comment by adamlawson** [comment] 2020-02-10 09:58
@asticode Do you have any tips/pointers on how to fix OS X and i'll have a go?

**Comment by asticode** [comment] 2020-02-10 11:17
Sure thing: the fix will need to occur in the [provisioner](https://github.com/asticode/go-astilectron/blob/master/provisioner.go). Basically a `Provisioner` is an interface with the method `Provision(ctx context.Context, appName, os, arch, versionAstilectron, versionElectron string, p Paths) error` that allows provisionning all the proper files based on the OS so that everything works properly. The default provisioner downloads both `Electron` and `Astilectron`, and makes the proper changes in the files.

And that's where it fails on MacOSX. If you take a look at [this method](https://github.com/asticode/go-astilectron/blob/master/provisioner.go#L209), it makes changes to MacOSX files so that the name that appears is the app name and not `Electron`. But it fails with the latest `electron` release. You'll need to update this logic.

Let me know if you need any clarification and thanks for having a go.

**Comment by aeroplanelabs** [comment] 2020-02-10 13:37
Some hints will be in this file, i attempted renaming the files (changes on my repo) but it didn't work when testing on a mac.
[electron-packager/mac.js](https://github.com/electron/electron-packager/blob/master/src/mac.js)

**Comment by adamlawson** [comment] 2020-02-10 16:26
Thanks both, I'll see how far I get with this tonight

**Comment by adamlawson** [comment] 2020-02-10 22:24
Pull Request created https://github.com/asticode/go-astilectron/pull/213

**Comment by asticode** [comment] 2020-02-11 08:47
I've merged the PR and I've also :

- bumped `astilectron` to `v0.35.0` (this version makes sure `nodeIntegration` is always `true`)
- removed `nodeIntegration` attribute in `window.go` since this attribute should always be true

I'll be updating module files of both bundler and demo.

Let me know if you experience any problem.

Thanks again to @adamlawson

**Closed** 2020-02-11 08:55 UTC
Labels: bug
